/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import DAO.Caso;
import DAO.Usuario;
import Logica.CasoLog;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javier
 */
public class Main extends javax.swing.JFrame {

    private String nombreUsuario;
    private Inicio inicioGUI;
    private CasoGUI casoGUI;
    private Incidente incidenteGUI;
    private SolicitudesGUI solicitudes;
    private CopiaImagen copiaImagen;

    private Usuario usuario;
    private CasoLog casolog;

    private DefaultTableModel modelo;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        usuario = new Usuario();

        iniciarSesion();
    }

    private void iniciarSesion() {
        this.show(false);
        inicioGUI = new Inicio(usuario);
        inicioGUI.show();
        inicioGUI.addWindowListener(new WindowListener() {

            public void windowOpened(WindowEvent e) {
            }

            public void windowClosing(WindowEvent e) {
            }

            public void windowClosed(WindowEvent e) {
                iniciar();
            }

            public void windowIconified(WindowEvent e) {
            }

            public void windowDeiconified(WindowEvent e) {
            }

            public void windowActivated(WindowEvent e) {
            }

            public void windowDeactivated(WindowEvent e) {
            }
        });
    }

    private void iniciar() {
        System.out.println("Iniciando sesion...");
        casolog = new CasoLog();

        cargarPerfil();

        cargarModelo();
        cargarCasos();
        revisarSolicitudesDeCaso();
//        revisarSolicitudesDeTraspaso();
        this.show();
        //Iniciar variables
        //extraer usuario
        //
        //
        //
    }

    private void cargarPerfil() {
        usuario = inicioGUI.getUsuario();
        menUsuario.setText(usuario.getNombre());
    }

    private void cargarModelo() {
        modelo = new DefaultTableModel();
        modelo.addColumn("Caso");
        modelo.addColumn("Detalle");
        modelo.addColumn("Rol");
        tblCasos.setModel(modelo);
    }

    private void cargarCasos() {
        String fila[] = new String[3];
        DefaultTableModel model = (DefaultTableModel) tblCasos.getModel();

        for (Caso caso : casolog.listarCasos(usuario.getId_persona())) {
            fila = new String[3];
            //TODO: LLenar tabla 
            fila[0] = caso.getReferencia();
            fila[1] = caso.getDetalles();
            fila[2] = caso.getRol();
            model.addRow(fila);
        }
    }

    private void revisarSolicitudesDeCaso() {
        int solicitudes = casolog.tieneSolicitudes(usuario.getId_persona());

        if (solicitudes > 0) {
            mitSolicitudes.setText("(" + solicitudes + ") Solicitud de caso");
            menCasos.setText("Casos *("+solicitudes+")");
        } else {
            mitSolicitudes.setText("Solicitud de caso");
            menCasos.setText("Casos");
        }

    }

//    private void revisarSolicitudesDeTraspaso() {
//        mitSolicitudTraspaso.setText("(2) " + mitSolicitudTraspaso.getText());
//        menTraspasos.setText("* " + menTraspasos.getText());
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCasos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnEvidencia = new javax.swing.JButton();
        barMenu = new javax.swing.JMenuBar();
        menCasos = new javax.swing.JMenu();
        mitNuevoCaso = new javax.swing.JMenuItem();
        mitSolicitudes = new javax.swing.JMenuItem();
        menAyuda = new javax.swing.JMenu();
        mitCopiarImagen = new javax.swing.JMenuItem();
        mitAcerca = new javax.swing.JMenuItem();
        menUsuario = new javax.swing.JMenu();
        mitCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblCasos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Caso", "Detalle", "Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCasos);

        jLabel2.setText("Casos");

        btnEvidencia.setText("Revisar Caso");
        btnEvidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvidenciaActionPerformed(evt);
            }
        });

        menCasos.setText("Casos");

        mitNuevoCaso.setText("Nuevo caso");
        mitNuevoCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNuevoCasoActionPerformed(evt);
            }
        });
        menCasos.add(mitNuevoCaso);

        mitSolicitudes.setText("Solicitud de caso");
        mitSolicitudes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSolicitudesActionPerformed(evt);
            }
        });
        menCasos.add(mitSolicitudes);

        barMenu.add(menCasos);

        menAyuda.setText("Herramientas");

        mitCopiarImagen.setText("Copiar Imagen");
        mitCopiarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitCopiarImagenActionPerformed(evt);
            }
        });
        menAyuda.add(mitCopiarImagen);

        mitAcerca.setText("Acerca de");
        menAyuda.add(mitAcerca);

        barMenu.add(menAyuda);

        menUsuario.setText("Javier");

        mitCerrarSesion.setText("Cerrar sesión");
        mitCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitCerrarSesionActionPerformed(evt);
            }
        });
        menUsuario.add(mitCerrarSesion);

        barMenu.add(menUsuario);

        setJMenuBar(barMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnEvidencia))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEvidencia)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEvidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvidenciaActionPerformed
        // TODO add your handling code here:        
        try {
            String caso = (String) tblCasos.getModel().getValueAt(tblCasos.getSelectedRow(), 0);
            String rol = (String) tblCasos.getModel().getValueAt(tblCasos.getSelectedRow(), 2);
            verCaso(caso, rol);
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("Debe seleccionar un caso");
        }
    }//GEN-LAST:event_btnEvidenciaActionPerformed

    private void mitCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitCerrarSesionActionPerformed
        // TODO add your handling code here:
        usuario = new Usuario();

        iniciarSesion();
    }//GEN-LAST:event_mitCerrarSesionActionPerformed

    private void mitNuevoCasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNuevoCasoActionPerformed
        // TODO add your handling code here:
        nuevoCaso();
    }//GEN-LAST:event_mitNuevoCasoActionPerformed

    private void mitSolicitudesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSolicitudesActionPerformed
        // TODO add your handling code here:
        this.show(false);
        solicitudes = new SolicitudesGUI(usuario.getId_persona());
        solicitudes.show();
        solicitudes.addWindowListener(new WindowListener() {

            public void windowOpened(WindowEvent e) {
            }

            public void windowClosing(WindowEvent e) {
            }

            public void windowClosed(WindowEvent e) {
                solicitudCerrada();
            }

            public void windowIconified(WindowEvent e) {
            }

            public void windowDeiconified(WindowEvent e) {
            }

            public void windowActivated(WindowEvent e) {
            }

            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_mitSolicitudesActionPerformed

    private void mitCopiarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitCopiarImagenActionPerformed
        
         this.show(false);
        copiaImagen = new CopiaImagen();
        copiaImagen.show();
        copiaImagen.addWindowListener(new WindowListener() {

            public void windowOpened(WindowEvent e) {
            }

            public void windowClosing(WindowEvent e) {
            }

            public void windowClosed(WindowEvent e) {
                abrirMain();
            }

            public void windowIconified(WindowEvent e) {
            }

            public void windowDeiconified(WindowEvent e) {
            }

            public void windowActivated(WindowEvent e) {
            }

            public void windowDeactivated(WindowEvent e) {
            }
        });
    }//GEN-LAST:event_mitCopiarImagenActionPerformed

    private void solicitudCerrada() {
        //cargar caso del id retornado 
        if (solicitudes.isAceptada()) {
            Caso caso = casolog.getCaso(solicitudes.getIdCasoAceptado());
            caso.setRol("INVESTIGADOR");
            if (caso.getId() > 0) {
                modelo.addRow(new String[]{caso.getReferencia(),caso.getDetalles(),caso.getRol()});
            }
        }
        this.show();
    }

    private void nuevoCaso() {
        this.show(false);
        incidenteGUI = new Incidente(usuario.getId_persona());
        incidenteGUI.show();
        incidenteGUI.addWindowListener(new WindowListener() {
            public void windowOpened(WindowEvent e) {
            }

            public void windowClosing(WindowEvent e) {
            }

            public void windowClosed(WindowEvent e) {
                actualizarCasos();
            }

            public void windowIconified(WindowEvent e) {
            }

            public void windowDeiconified(WindowEvent e) {
            }

            public void windowActivated(WindowEvent e) {
            }

            public void windowDeactivated(WindowEvent e) {
            }
        });
    }

    private void verCaso(String refCaso, String rol) {
        this.show(false);
        casoGUI = new CasoGUI(refCaso, usuario.getId_persona(), rol);
        casoGUI.show();
        casoGUI.addWindowListener(new WindowListener() {
            public void windowOpened(WindowEvent e) {
            }

            public void windowClosing(WindowEvent e) {
            }

            public void windowClosed(WindowEvent e) {
                abrirMain();
            }

            public void windowIconified(WindowEvent e) {
            }

            public void windowDeiconified(WindowEvent e) {
            }

            public void windowActivated(WindowEvent e) {
            }

            public void windowDeactivated(WindowEvent e) {
            }
        });
    }

    private void actualizarCasos() {
        DefaultTableModel model = (DefaultTableModel) tblCasos.getModel();
        String fila[] = new String[3];
        fila[0] = incidenteGUI.getCasolog().getObjCaso().getReferencia();
        fila[1] = incidenteGUI.getCasolog().getObjCaso().getDetalles();
        fila[2] = "ADMINISTRADOR";
        model.addRow(fila);
        this.show();
    }

    private void abrirMain() {
        this.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JButton btnEvidencia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menAyuda;
    private javax.swing.JMenu menCasos;
    private javax.swing.JMenu menUsuario;
    private javax.swing.JMenuItem mitAcerca;
    private javax.swing.JMenuItem mitCerrarSesion;
    private javax.swing.JMenuItem mitCopiarImagen;
    private javax.swing.JMenuItem mitNuevoCaso;
    private javax.swing.JMenuItem mitSolicitudes;
    private javax.swing.JTable tblCasos;
    // End of variables declaration//GEN-END:variables
}
